### PR TITLE
Remove unused button in both delete Windows and fix in JOptionPane message

### PR DESCRIPTION
**Pull request by Andoni-S**
We have removed some unused buttons on the delete windows and fixed a message on a JOptionPane in the DeleteSCP windows preparing for the video for the final presentation

### CODE REVIEW

**Comment by Andoni-S** [comment]
Os parecen bien los cambios?

**Comment by MeylinM** [comment]
I think that is okay

**Comment by alex29122000** [comment]
Everything OK

**Comment by irodrigon** [comment]
Seems allright, thank you.

**Pull request merged**
